site_name: MinVar

docs_dir: rtd

pages:
    - Introduction: 'index.md'
    - User Guide:
        - 'Installation': 'user-guide/installation.md'
        - 'Output files': 'user-guide/output-files.md'
    - 'License': 'license.md'
